### ISSUE TITLE
Protection stat

### ISSUE THREAD

**Issue by Darxide23** [AntoineThebaud/swlcalc#4]
Protection stat doesn't seem to update. It should ideally also show the % damage reduction.

![Untitled](https://user-images.githubusercontent.com/41874525/101444143-7a456800-38e4-11eb-9c5b-bc3a00a352a6.png)

**Comment by AntoineThebaud** [comment]
Hello @Darxide23, thanks for your feedback.

Protection is not implemented currently, that's why it is grayed out in the summary. I'm busy with another project right now, but when I'll be working back on swlcalc this is actually the next feature I already planned to implement (See https://github.com/AntoineThebaud/swlcalc/projects/1#card-8130997)

**Comment by AntoineThebaud** [comment]
Protection is now available in swlcalc :)
